
version: '3.9'

services:
  app:
    container_name: docker-practice-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '8018:80'
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html

  db:
    container_name: docker-practice-db
    image: mysql:8.0
    volumes:
      - type: volume
        source: docker-file-practice-db-store
        target: /var/lib/mysql
      - type: bind
        source: ./sql/createMemoTable.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-compose-practice-db

volumes:
  docker-file-practice-db-store: