
version: '3.9'

services:
  app:
    container_name: docker-practice-app
    image: php:8.1.4-apache
    ports:
      - '8018:80'
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html

  db:
    container_name: docker-practice-db
    image: mysql:8.0
    volumes:
      - type: volume
        source: docker-practice-db-store
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-compose-practice-db

volumes:
  docker-practice-db-store: